# Generated by Django 2.0.5 on 2018-09-11 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharma_track', '0004_auto_20180911_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nct_id', models.CharField(max_length=400, verbose_name='NCT Number')),
                ('title', models.CharField(max_length=400, verbose_name='Title')),
                ('acronym', models.CharField(max_length=400, verbose_name='Acronym')),
                ('status', models.CharField(max_length=400, verbose_name='Status')),
                ('study_results', models.CharField(max_length=400, verbose_name='Study Results')),
                ('interventions', models.CharField(max_length=400, verbose_name='Interventions')),
                ('outcome_measures', models.CharField(max_length=400, verbose_name='Outcome Measures')),
                ('sponsor', models.CharField(max_length=400, verbose_name='Sponsor/Collaborators')),
                ('gender', models.CharField(max_length=400, verbose_name='Gender')),
                ('age', models.CharField(max_length=400, verbose_name='Age')),
                ('phase', models.CharField(max_length=400, verbose_name='Phase')),
                ('funded_by', models.CharField(max_length=400, verbose_name='Funded Bys')),
                ('study_type', models.CharField(max_length=400, verbose_name='Study Type')),
                ('study_design', models.CharField(max_length=400, verbose_name='Study Designs')),
                ('other_ids', models.CharField(max_length=400, verbose_name='Other IDs')),
                ('start_date', models.CharField(max_length=400, verbose_name='Start Date')),
                ('primary_completion_date', models.CharField(max_length=400, verbose_name='Primary Completion Date')),
                ('completion_date', models.CharField(max_length=400, verbose_name='Completion Date')),
                ('first_posted', models.CharField(max_length=400, verbose_name='First Posted')),
                ('results_first_posted', models.CharField(max_length=400, verbose_name='Results First Posted')),
                ('last_update_posted', models.CharField(max_length=400, verbose_name='Last Update Posted')),
                ('locations', models.CharField(max_length=400, verbose_name='Locations')),
                ('study_documents', models.CharField(max_length=400, verbose_name='Study Documents')),
                ('url', models.CharField(max_length=400, verbose_name='URL')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studies', to='pharma_track.Drug')),
            ],
            options={
                'verbose_name': 'Study',
                'verbose_name_plural': 'Studies',
            },
        ),
    ]
