# Generated by Django 2.0.5 on 2018-09-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma_track', '0005_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='conditions',
            field=models.CharField(default='', max_length=400, verbose_name='Conditions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='study',
            name='enrollment',
            field=models.CharField(default='', max_length=400, verbose_name='Enrollment'),
            preserve_default=False,
        ),
    ]
