# Generated by Django 2.0.5 on 2018-09-25 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma_track', '0006_auto_20180911_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='source',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
